package forge.net;

import forge.deck.Deck;
import forge.deck.DeckSection;
import forge.game.Game;
import forge.game.GameObject;
import forge.game.GameStage;
import forge.game.ability.AbilityFactory;
import forge.game.card.Card;
import forge.game.player.Player;
import forge.game.spellability.SpellAbility;
import forge.game.zone.ZoneType;
import forge.gamemodes.match.input.ExternalDecisionRequest;
import forge.gamemodes.match.input.ExternalDecisionResponse;
import forge.gamemodes.match.input.ExternalDecisionTape;
import forge.gamemodes.match.input.ExternalDecisionValidationException;
import forge.item.PaperCard;
import forge.model.FModel;
import forge.player.PlayerControllerHuman;
import forge.util.MyRandom;
import org.testng.annotations.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Comparator;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;

/** WS31 exact-path hidden/RNG/replay qualification campaign. */
public final class Ws31HiddenRngReplayQualificationTest {
    private static final String GAME_ID = "ws31-hidden-rng-replay-4p";
    private static final long SEED = 3131313131L;
    private static final String SECRET = "Black Lotus";

    private static final class CaseSpec {
        final int ordinal; final String pathId,oracleId,cardName,dispatch,implementation,sourcePath,sourceDirective,sourceToken,script; final int sourceLine; final boolean hidden,rng,replay,decision;
        CaseSpec(String[] f){ordinal=Integer.parseInt(f[0]);pathId=f[1];oracleId=f[2];cardName=f[3];dispatch=f[4];implementation=f[5];sourcePath=f[6];sourceLine=Integer.parseInt(f[7]);sourceDirective=f[8];sourceToken=f[9];hidden="1".equals(f[10]);rng="1".equals(f[11]);replay="1".equals(f[12]);decision="1".equals(f[13]);script=new String(Base64.getDecoder().decode(f[14]),StandardCharsets.UTF_8);}
    }
    private static final class CaseEvidence {
        final CaseSpec spec; String status="UNKNOWN",failureType="",failureMessage="",beforeDigest="",afterDigest="",beforeState="",afterState=""; long decisionEvents,rngEvents,leakDelta,crossPrincipalDelta;
        final Map<Integer,Long> principalRequests=new LinkedHashMap<>(); final Map<Integer,Long> principalCardOptionRequests=new LinkedHashMap<>(); final Set<Integer> authorizedDecisionPrincipals=new LinkedHashSet<>();
        CaseEvidence(CaseSpec s){spec=s;}
    }
    private interface DecisionSource { ExternalDecisionResponse decide(Player player,ExternalDecisionRequest request,String pathId); default void assertConsumed(){} }
    private static final class RecordPolicy implements DecisionSource {
        @Override public ExternalDecisionResponse decide(Player player,ExternalDecisionRequest request,String pathId){List<String> selected=new ArrayList<>();if("MULLIGAN".equals(request.getDecisionKind()))selected.add(requireSemantic(request,"true"));else if("PRIORITY_ACTION".equals(request.getDecisionKind())&&pathId==null)selected.add(requireSemantic(request,"PASS_PRIORITY"));else if(("STARTING_PLAYER".equals(request.getDecisionKind())||"STARTING_HAND".equals(request.getDecisionKind()))&&pathId==null)selectByPathPolicy(request,"startup:"+request.getDecisionKind(),selected,false);else if(pathId!=null)selectByPathPolicy(request,pathId,selected,true);else throw new ExternalDecisionValidationException(ExternalDecisionValidationException.Code.UNSUPPORTED_DECISION_PATH,"WS31 has no explicit qualification policy for out-of-campaign decision "+request.getDecisionKind());return response(request,selected);}
    }
    private static final class DecisionReplay implements DecisionSource {
        private static final class Line {final long eventId,decisionId,token;final String kind;final int actor,principal;final List<String> selected;Line(long e,long d,long t,String k,int a,int p,List<String>s){eventId=e;decisionId=d;token=t;kind=k;actor=a;principal=p;selected=s;}}
        final Map<Integer,List<Line>> byPrincipal=new HashMap<>(); final Map<Integer,AtomicInteger> index=new ConcurrentHashMap<>();
        static DecisionReplay load(Path path)throws IOException{DecisionReplay r=new DecisionReplay();for(String line:Files.readAllLines(path,StandardCharsets.UTF_8)){if(line.isBlank())continue;String[]f=line.split("\\t",-1);if(f.length!=8)throw new IllegalArgumentException("bad decision tape row");int n=Integer.parseInt(f[6]);List<String>selected=new ArrayList<>();if(n>0){String[]es=f[7].split(",",-1);if(es.length!=n)throw new IllegalArgumentException("decision count mismatch");for(String e:es)selected.add(dec(e));}Line x=new Line(Long.parseLong(f[0]),Long.parseLong(f[1]),Long.parseLong(f[2]),dec(f[3]),Integer.parseInt(f[4]),Integer.parseInt(f[5]),selected);r.byPrincipal.computeIfAbsent(x.principal,k->new ArrayList<>()).add(x);}if(r.byPrincipal.isEmpty())throw new IllegalArgumentException("empty decision replay tape");return r;}
        @Override public ExternalDecisionResponse decide(Player player,ExternalDecisionRequest request,String pathId){int p=request.getPrincipalId();List<Line> lines=byPrincipal.get(p);if(lines==null)throw new IllegalStateException("no replay principal "+p);int i=index.computeIfAbsent(p,k->new AtomicInteger()).getAndIncrement();if(i>=lines.size())throw new IllegalStateException("decision tape exhausted principal="+p);Line x=lines.get(i);eq("decision_id",x.decisionId,request.getDecisionId());eq("token",x.token,request.getToken());if(!x.kind.equals(request.getDecisionKind())||x.actor!=request.getActorId()||x.principal!=request.getPrincipalId())throw new IllegalStateException("decision replay semantic mismatch expected="+x.kind+" actual="+request.getDecisionKind());return response(request,x.selected);}
        @Override public void assertConsumed(){for(var e:byPrincipal.entrySet()){int got=index.getOrDefault(e.getKey(),new AtomicInteger()).get();if(got!=e.getValue().size())throw new IllegalStateException("decision tape unconsumed principal="+e.getKey()+" got="+got+" expected="+e.getValue().size());}}
    }
    private static final class RngReplay implements MyRandom.ReplayProvider {
        private static final class Line{final long eventId,draw;final String game,stream;final int bits,value;Line(long e,String g,String s,long d,int b,int v){eventId=e;game=g;stream=s;draw=d;bits=b;value=v;}}
        final List<Line> lines=new ArrayList<>();int index;
        static RngReplay load(Path path)throws IOException{RngReplay r=new RngReplay();for(String line:Files.readAllLines(path,StandardCharsets.UTF_8)){if(line.isBlank())continue;String[]f=line.split("\\t",-1);if(f.length!=6)throw new IllegalArgumentException("bad rng tape row");r.lines.add(new Line(Long.parseLong(f[0]),dec(f[1]),dec(f[2]),Long.parseLong(f[3]),Integer.parseInt(f[4]),Integer.parseInt(f[5])));}if(r.lines.isEmpty())throw new IllegalArgumentException("empty rng replay tape");return r;}
        @Override public int next(MyRandom.RngRequest request){if(index>=lines.size())throw new IllegalStateException("rng tape exhausted");Line x=lines.get(index++);eq("rng_event",x.eventId,request.getEventId());if(!x.game.equals(request.getGameId())||!x.stream.equals(request.getStream())||x.draw!=request.getDrawIndex()||x.bits!=request.getBits())throw new IllegalStateException("rng replay semantic mismatch");return x.value;}void assertConsumed(){if(index!=lines.size())throw new IllegalStateException("rng tape unconsumed="+(lines.size()-index));}
    }

    @Test(timeOut=600_000)
    public void ws31Campaign()throws Exception{
        final Path casesPath=required("ws31.cases"),outDir=required("ws31.outDir");Files.createDirectories(outDir);final String mode=System.getProperty("ws31.mode","record");final boolean isReplay="replay".equals(mode);if(!isReplay&&!"record".equals(mode))throw new IllegalArgumentException("ws31.mode");final List<CaseSpec> cases=loadCases(casesPath);if(cases.size()!=81)throw new IllegalStateException("WS31 expected 81 cases, got "+cases.size());TestUtils.ensureFModelInitialized();
        final DecisionSource decisionSource=isReplay?DecisionReplay.load(required("ws31.decisionReplay")):new RecordPolicy();final RngReplay rngReplay=isReplay?RngReplay.load(required("ws31.rngReplay")):null;final AtomicReference<String> currentPath=new AtomicReference<>();final Map<String,CaseEvidence> evidence=new LinkedHashMap<>();for(CaseSpec c:cases)evidence.put(c.pathId,new CaseEvidence(c));final CopyOnWriteArrayList<MyRandom.RngEvent> allRng=new CopyOnWriteArrayList<>();final CopyOnWriteArrayList<String> rngPath=new CopyOnWriteArrayList<>();final CopyOnWriteArrayList<ExternalDecisionTape.Event> allDecisions=new CopyOnWriteArrayList<>();final CopyOnWriteArrayList<String> decisionPath=new CopyOnWriteArrayList<>();final AtomicBoolean campaignStarted=new AtomicBoolean();final AtomicReference<Throwable> campaignFailure=new AtomicReference<>();
        Ws05HiddenInfoProbe.reset();Ws05HiddenInfoProbe.registerSecret(SECRET);System.setProperty("forge.ws01.externalHumanHost","true");System.setProperty("forge.ws06.strictGameRng","true");MyRandom.beginGameScope(GAME_ID,SEED,event->{allRng.add(event);rngPath.add(currentPath.get());String p=currentPath.get();if(p!=null)evidence.get(p).rngEvents++;},rngReplay);ExternalDecisionTape.setEventObserver(event->{allDecisions.add(event);decisionPath.add(currentPath.get());Ws05HiddenInfoProbe.observeReplay(event);String p=currentPath.get();if(p!=null)evidence.get(p).decisionEvents++;});
        PlayerControllerHuman.setExternalDecisionProviderFactory(player->request->{String p=currentPath.get();if(p!=null){CaseEvidence ce=evidence.get(p);ce.principalRequests.merge(request.getPrincipalId(),1L,Long::sum);ce.authorizedDecisionPrincipals.add(request.getPrincipalId());boolean card=false;for(ExternalDecisionRequest.Option o:request.getOptions())if(String.valueOf(o.getEntityKind()).toLowerCase().contains("card"))card=true;if(card)ce.principalCardOptionRequests.merge(request.getPrincipalId(),1L,Long::sum);}Ws05HiddenInfoProbe.observeDecision(player.getName(),player.getId(),request);return decisionSource.decide(player,request,p);});
        Game.setSemanticStateObserver((game,checkpoint)->{if(!campaignStarted.get()&&ready(game)&&campaignStarted.compareAndSet(false,true)){try{runCampaign(game,cases,evidence,currentPath);}catch(Throwable t){campaignFailure.set(t);Ws05HiddenInfoProbe.observeException(t);}finally{currentPath.set(null);List<Player>ps=players(game);for(int i=1;i<ps.size();i++)ps.get(i).concede();game.getAction().checkStateEffects(true);}}});
        UnifiedNetworkHarness.GameResult result=null;Throwable outer=null;try{result=new UnifiedNetworkHarness().playerCount(4).remoteClients(3).useAiForRemotePlayers(false).commander(true).decks(createDecks()).gameTimeout(240000).execute();if(!campaignStarted.get())throw new IllegalStateException("WS31 campaign never reached ready 4P game");if(campaignFailure.get()!=null)throw new IllegalStateException("WS31 campaign failure",campaignFailure.get());if(isReplay){rngReplay.assertConsumed();decisionSource.assertConsumed();}}catch(Throwable t){outer=t;Ws05HiddenInfoProbe.observeException(t);}finally{writeEvidence(outDir,mode,cases,evidence,allRng,rngPath,allDecisions,decisionPath,result,outer);PlayerControllerHuman.setExternalDecisionProviderFactory(null);ExternalDecisionTape.setEventObserver(null);Game.setSemanticStateObserver(null);MyRandom.endGameScope();System.clearProperty("forge.ws06.strictGameRng");System.clearProperty("forge.ws01.externalHumanHost");}if(outer!=null){if(outer instanceof Exception)throw(Exception)outer;throw new RuntimeException(outer);}
    }
    private static boolean ready(Game game){if(game.getAge()!=GameStage.Play||game.getRegisteredPlayers().size()!=4)return false;for(Player p:game.getRegisteredPlayers())if(!(p.getController() instanceof PlayerControllerHuman))return false;return true;}
    private static void runCampaign(Game game,List<CaseSpec>cases,Map<String,CaseEvidence>evidence,AtomicReference<String>currentPath){List<Player>ps=players(game);Player actor=ps.get(1),opponent=ps.get(2);for(CaseSpec spec:cases){CaseEvidence ce=evidence.get(spec.pathId);currentPath.set(spec.pathId);long leak0=Ws05HiddenInfoProbe.pilotVisibleLeaks(),cross0=Ws05HiddenInfoProbe.crossPrincipalLeaks();try{seedCommon(game,actor,opponent);Card canary=addCard(SECRET,actor,ZoneType.Library);Ws05HiddenInfoProbe.setPhase(spec.pathId,canary.getId(),Set.of());Card source=addCard(spec.cardName,actor,ZoneType.Battlefield);source.addRemembered(opponent);source.addRemembered(addCard("Runeclaw Bear",opponent,ZoneType.Battlefield));opponent.setNamedCard("Runeclaw Bear");actor.setNamedCard("Runeclaw Bear");SpellAbility sa=AbilityFactory.getAbility(spec.script,source);sa.setActivatingPlayer(actor);if(sa.getApi()==null||!spec.dispatch.equals(sa.getApi().name()))throw new IllegalStateException("dispatch mismatch runtime="+(sa.getApi()==null?"null":sa.getApi().name()));bindTarget(sa,game,actor,opponent);ce.beforeState=semanticState(game);ce.beforeDigest=sha256(ce.beforeState);sa.resolve();game.getAction().checkStateEffects(true);ce.afterState=semanticState(game);ce.afterDigest=sha256(ce.afterState);ce.status="PASS";}catch(Throwable t){ce.status="FAIL";ce.failureType=t.getClass().getName();ce.failureMessage=sanitize(String.valueOf(t.getMessage()));Ws05HiddenInfoProbe.observeException(t);}finally{ce.leakDelta=Ws05HiddenInfoProbe.pilotVisibleLeaks()-leak0;ce.crossPrincipalDelta=Ws05HiddenInfoProbe.crossPrincipalLeaks()-cross0;for(Player p:ps){ce.principalRequests.putIfAbsent(p.getId(),0L);ce.principalCardOptionRequests.putIfAbsent(p.getId(),0L);}currentPath.set(null);}}}
    private static void seedCommon(Game game,Player actor,Player opponent){String[]library={"Sol Ring","Island","Serra Angel","Lightning Bolt","Darksteel Ingot","Runeclaw Bear","Plains","Grizzly Bears","Ornithopter","Forest","Mountain","Swamp"};for(String n:library){addCard(n,actor,ZoneType.Library);addCard(n,opponent,ZoneType.Library);}for(int i=0;i<3;i++){addCard("Runeclaw Bear",actor,ZoneType.Hand);addCard("Grizzly Bears",opponent,ZoneType.Hand);}}
    private static void bindTarget(SpellAbility sa,Game game,Player actor,Player opponent){if(!sa.usesTargeting())return;List<GameObject>candidates=new ArrayList<>();candidates.add(opponent);candidates.add(actor);for(Player p:game.getPlayers())if(!candidates.contains(p))candidates.add(p);for(Card c:game.getCardsInGame())candidates.add(c);for(GameObject c:candidates){try{if(sa.canTarget(c)){sa.getTargets().add(c);return;}}catch(RuntimeException ignored){}}throw new IllegalStateException("no legal target available for exact path");}
    private static Card addCard(String name,Player player,ZoneType zone){PaperCard pc=FModel.getMagicDb().getCommonCards().getCard(name);if(pc==null)throw new IllegalStateException("card unavailable: "+name);Card c=Card.fromPaperCard(pc,player);c.setGameTimestamp(player.getGame().getNextTimestamp());player.getZone(zone).add(c);return c;}
    private static void selectByPathPolicy(ExternalDecisionRequest req,String path,List<String>selected,boolean exerciseOptional){List<ExternalDecisionRequest.Option>options=new ArrayList<>(req.getOptions());if(options.isEmpty()){if(req.getMinimumSelection()==0)return;throw new ExternalDecisionValidationException(ExternalDecisionValidationException.Code.ILLEGAL_OPTION,"empty authoritative option set for "+req.getDecisionKind());}for(ExternalDecisionRequest.Option o:options)if(exerciseOptional&&"true".equalsIgnoreCase(o.getSemanticValue())){selected.add(o.getOptionId());return;}options.sort(Comparator.comparing(o->stableKey(path,req.getDecisionKind(),o)));int min=req.getMinimumSelection(),max=req.getMaximumSelection(),count=min;if(exerciseOptional&&count==0&&max>0)count=1;if(count<0||count>max||count>options.size())throw new ExternalDecisionValidationException(ExternalDecisionValidationException.Code.UNSUPPORTED_DECISION_PATH,"invalid cardinality "+req.getDecisionKind());for(int i=0;i<count;i++)selected.add(options.get(i).getOptionId());}
    private static String stableKey(String path,String kind,ExternalDecisionRequest.Option o){return sha256(path+"|"+kind+"|"+String.valueOf(o.getEntityKind())+"|"+String.valueOf(o.getSemanticValue())+"|"+o.getOptionId());}
    private static String requireSemantic(ExternalDecisionRequest req,String semantic){for(ExternalDecisionRequest.Option o:req.getOptions())if(semantic.equals(o.getSemanticValue()))return o.getOptionId();throw new ExternalDecisionValidationException(ExternalDecisionValidationException.Code.ILLEGAL_OPTION,"missing semantic option "+semantic+" for "+req.getDecisionKind());}
    private static ExternalDecisionResponse response(ExternalDecisionRequest r,List<String>s){return new ExternalDecisionResponse(r.getDecisionId(),r.getToken(),r.getActorId(),r.getPrincipalId(),r.getResponseSchema(),s,false);}
    private static List<CaseSpec>loadCases(Path p)throws IOException{List<CaseSpec>out=new ArrayList<>();for(String line:Files.readAllLines(p,StandardCharsets.UTF_8)){if(line.isBlank())continue;String[]f=line.split("\\t",-1);if(f.length!=15)throw new IllegalArgumentException("bad case TSV fields="+f.length);out.add(new CaseSpec(f));}return out;}
    private static List<Player>players(Game game){List<Player>p=new ArrayList<>();for(Player x:game.getRegisteredPlayers())p.add(x);p.sort(Comparator.comparingInt(Player::getId));return p;}
    private static List<Deck>createDecks(){List<Deck>d=new ArrayList<>();PaperCard commander=FModel.getMagicDb().getCommonCards().getCard("Isamaru, Hound of Konda");if(commander==null)throw new IllegalStateException("commander unavailable");for(int i=0;i<4;i++){Deck x=TestDeckLoader.createMinimalDeck("Plains",12);x.getOrCreate(DeckSection.Commander).add(commander);d.add(x);}return d;}
    private static String semanticState(Game game){StringBuilder s=new StringBuilder();for(Player p:players(game)){s.append("P|").append(p.getId()).append('|').append(p.getLife());for(ZoneType z:new ZoneType[]{ZoneType.Library,ZoneType.Hand,ZoneType.Battlefield,ZoneType.Graveyard,ZoneType.Exile,ZoneType.Command}){s.append('|').append(z.name()).append(':');List<String>names=new ArrayList<>();for(Card c:p.getCardsIn(z))names.add(c.getName());if(z!=ZoneType.Library)names.sort(String::compareTo);for(String n:names)s.append(n).append(',');}}return s.toString();}
    private static String sha256(String value){try{byte[]d=MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();for(byte b:d)s.append(String.format("%02x",b));return s.toString();}catch(Exception e){throw new IllegalStateException(e);}}
    private static String sanitize(String s){if(s==null)return"";return s.replace(SECRET,"<private-card>").replace('\t',' ').replace('\n',' ').replace('\r',' ');}
    private static Path required(String prop){String v=System.getProperty(prop);if(v==null||v.isBlank())throw new IllegalStateException(prop+" required");return Path.of(v);}
    private static String enc(String s){return Base64.getEncoder().encodeToString((s==null?"":s).getBytes(StandardCharsets.UTF_8));}private static String dec(String s){return new String(Base64.getDecoder().decode(s),StandardCharsets.UTF_8);}private static void eq(String f,long a,long b){if(a!=b)throw new IllegalStateException("replay mismatch "+f+" expected="+a+" actual="+b);}
    private static void writeEvidence(Path out,String mode,List<CaseSpec>cases,Map<String,CaseEvidence>ev,List<MyRandom.RngEvent>rng,List<String>rngPaths,List<ExternalDecisionTape.Event>decisions,List<String>decPaths,UnifiedNetworkHarness.GameResult result,Throwable outer)throws IOException{
        try(var w=Files.newBufferedWriter(out.resolve("case-summary.tsv"),StandardCharsets.UTF_8)){for(CaseSpec c:cases){CaseEvidence e=ev.get(c.pathId);StringBuilder pr=new StringBuilder(),cr=new StringBuilder(),ap=new StringBuilder();for(var x:e.principalRequests.entrySet()){if(pr.length()>0)pr.append(',');pr.append(x.getKey()).append(':').append(x.getValue());}for(var x:e.principalCardOptionRequests.entrySet()){if(cr.length()>0)cr.append(',');cr.append(x.getKey()).append(':').append(x.getValue());}for(Integer x:e.authorizedDecisionPrincipals){if(ap.length()>0)ap.append(',');ap.append(x);}w.write(String.join("\t",c.pathId,c.oracleId,c.dispatch,c.implementation,e.status,e.beforeDigest,e.afterDigest,Long.toString(e.decisionEvents),Long.toString(e.rngEvents),Long.toString(e.leakDelta),Long.toString(e.crossPrincipalDelta),pr.toString(),cr.toString(),ap.toString(),enc(e.failureType),enc(e.failureMessage),enc(e.beforeState),enc(e.afterState)));w.newLine();}}
        try(var w=Files.newBufferedWriter(out.resolve("rng-tape.tsv"),StandardCharsets.UTF_8)){for(MyRandom.RngEvent e:rng){w.write(e.getEventId()+"\t"+enc(e.getGameId())+"\t"+enc(e.getStream())+"\t"+e.getDrawIndex()+"\t"+e.getBits()+"\t"+e.getValue());w.newLine();}}
        try(var w=Files.newBufferedWriter(out.resolve("rng-events-with-path.tsv"),StandardCharsets.UTF_8)){for(int i=0;i<rng.size();i++){MyRandom.RngEvent e=rng.get(i);w.write(enc(String.valueOf(rngPaths.get(i)))+"\t"+e.getEventId()+"\t"+enc(e.getGameId())+"\t"+enc(e.getStream())+"\t"+e.getDrawIndex()+"\t"+e.getBits()+"\t"+e.getValue());w.newLine();}}
        List<ExternalDecisionTape.Event>canonical=new ArrayList<>(decisions);canonical.sort((a,b)->{int p=Integer.compare(a.getPrincipalId(),b.getPrincipalId());return p!=0?p:Long.compare(a.getEventId(),b.getEventId());});try(var w=Files.newBufferedWriter(out.resolve("decision-tape.tsv"),StandardCharsets.UTF_8)){for(ExternalDecisionTape.Event e:canonical){List<String>s=e.getSelectedOptionIds();StringBuilder b=new StringBuilder();for(String x:s){if(b.length()>0)b.append(',');b.append(enc(x));}w.write(e.getEventId()+"\t"+e.getDecisionId()+"\t"+e.getToken()+"\t"+enc(e.getDecisionKind())+"\t"+e.getActorId()+"\t"+e.getPrincipalId()+"\t"+s.size()+"\t"+b);w.newLine();}}
        try(var w=Files.newBufferedWriter(out.resolve("decision-events-with-path.tsv"),StandardCharsets.UTF_8)){for(int i=0;i<decisions.size();i++){ExternalDecisionTape.Event e=decisions.get(i);w.write(enc(String.valueOf(decPaths.get(i)))+"\t"+e.getEventId()+"\t"+enc(e.getDecisionKind())+"\t"+e.getActorId()+"\t"+e.getPrincipalId()+"\t"+e.getResponseStatus()+"\t"+enc(String.valueOf(e.getErrorCode())));w.newLine();}}
        String meta="{\n  \"schema\":\"commander-simulator-next.ws31-process.v1\",\n  \"mode\":\""+mode+"\",\n  \"evidence_visibility\":\"QUALIFICATION_PRIVATE\",\n  \"game_completed\":"+(result!=null&&result.gameCompleted)+",\n  \"path_count\":"+cases.size()+",\n  \"pilot_visible_hidden_info_leaks\":"+Ws05HiddenInfoProbe.pilotVisibleLeaks()+",\n  \"cross_principal_decision_leaks\":"+Ws05HiddenInfoProbe.crossPrincipalLeaks()+",\n  \"phase_mismatches\":"+Ws05HiddenInfoProbe.phaseMismatchCount()+",\n  \"outer_failure\":"+(outer==null?"null":"{\"type\":\""+enc(outer.getClass().getName())+"\",\"message_b64\":\""+enc(sanitize(String.valueOf(outer.getMessage())))+"\"}")+"\n}\n";Files.writeString(out.resolve("process.json"),meta,StandardCharsets.UTF_8);
    }
}
